version: '3.8'

services:
  # 1. Aplicación Unicornio (Entorno DEV)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unicornio_app_dev
    ports:
      - "80:80" # Acceso web directo (localhost)
    volumes:
      - .:/var/www/html # HOT RELOAD: Mapea carpeta actual al contenedor
    environment:
      - APP_ENV=development
      - DB_HOST=db
      - DB_NAME=unicornio
      - DB_USER=root
      - DB_PASS=root
    networks:
      - dev-network
    depends_on:
      - db

  # 2. Base de Datos Local
  db:
    image: mariadb:10.6
    container_name: unicornio_db_dev
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=unicornio
    volumes:
      - db_data_dev:/var/lib/mysql
      # Inicializa BD con el schema limpio si no existe
      - ./bd-sql/schema_clean.sql:/docker-entrypoint-initdb.d/1_schema.sql
    networks:
      - dev-network
    ports:
      - "3306:3306" # Expuesto para conectar herramientas externas (HeidiSQL, DBeaver)

  # 3. PHPMyAdmin (Reemplazo visual de XAMPP)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: unicornio_pma
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80" # Acceso en http://localhost:8080
    networks:
      - dev-network
    depends_on:
      - db

volumes:
  db_data_dev:


networks:
  dev-network:
    driver: bridge
